
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/scan-icons.js
 */
export const ICON_DATA = {
    "usage": {
        "arrow-left": [
            "approval-detail.component.html",
            "command-center-layout.component.ts",
            "dev-layout.component.ts"
        ],
        "hourglass": [
            "approval-detail.component.html"
        ],
        "check-circle": [
            "approval-detail.component.html",
            "approvals-dashboard.component.html",
            "command-center-layout.component.ts",
            "operational-metrics.component.html"
        ],
        "x-circle": [
            "approval-detail.component.html",
            "approvals-dashboard.component.html",
            "inventory-analytics.component.html",
            "data-seeder.component.ts"
        ],
        "slash": [
            "approval-detail.component.html"
        ],
        "check": [
            "approval-detail.component.html",
            "data-seeder.component.ts",
            "approval-card.component.ts"
        ],
        "x": [
            "approval-detail.component.html",
            "log-explorer.component.ts",
            "approval-card.component.ts"
        ],
        "clock": [
            "approvals-dashboard.component.html",
            "operational-metrics.component.html"
        ],
        "document": [
            "approvals-dashboard.component.html",
            "command-center-layout.component.ts",
            "expense-management.component.html",
            "income-statement.component.html"
        ],
        "command-center": [
            "command-center-layout.component.ts",
            "command-center-dashboard.component.html"
        ],
        "dashboard": [
            "command-center-layout.component.ts"
        ],
        "activity": [
            "command-center-layout.component.ts",
            "sales-analytics.component.html",
            "config.component.ts",
            "data-seeder.component.ts",
            "dev-layout.component.ts",
            "state-inspector.component.ts"
        ],
        "chart-pie": [
            "command-center-layout.component.ts"
        ],
        "wallet": [
            "command-center-layout.component.ts",
            "expense-management.component.html",
            "income-statement.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html"
        ],
        "users": [
            "command-center-layout.component.ts",
            "customer-insights.component.html",
            "sales-analytics.component.html"
        ],
        "chart-bar": [
            "command-center-layout.component.ts",
            "expense-management.component.html",
            "income-statement.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html"
        ],
        "box": [
            "command-center-layout.component.ts",
            "income-statement.component.html",
            "inventory-analytics.component.html",
            "operational-metrics.component.html",
            "sales-analytics.component.html",
            "state-inspector.component.ts"
        ],
        "chevron-down": [
            "command-center-layout.component.ts"
        ],
        "refresh-cw": [
            "command-center-layout.component.ts",
            "expense-management.component.html",
            "inventory-analytics.component.html",
            "firestore-monitor.component.ts",
            "state-inspector.component.ts"
        ],
        "home": [
            "command-center-layout.component.ts",
            "sales-analytics.component.html"
        ],
        "log-out": [
            "command-center-layout.component.ts"
        ],
        "alert-triangle": [
            "customer-insights.component.html",
            "inventory-analytics.component.html",
            "operational-metrics.component.html",
            "data-seeder.component.ts",
            "i18n-studio.component.ts"
        ],
        "grid": [
            "expense-management.component.html",
            "dev-layout.component.ts"
        ],
        "list": [
            "expense-management.component.html"
        ],
        "download": [
            "expense-management.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html",
            "state-inspector.component.ts"
        ],
        "trending-up": [
            "expense-management.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html",
            "dev-layout.component.ts"
        ],
        "edit": [
            "expense-management.component.html",
            "firestore-monitor.component.ts"
        ],
        "trash": [
            "expense-management.component.html",
            "config.component.ts"
        ],
        "calendar": [
            "expense-management.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html"
        ],
        "briefcase": [
            "expense-management.component.html",
            "income-statement.component.html"
        ],
        "banknote": [
            "financial-dashboard.component.html",
            "inventory-analytics.component.html",
            "sales-analytics.component.html"
        ],
        "target": [
            "income-statement.component.html"
        ],
        "lightning": [
            "inventory-analytics.component.html"
        ],
        "skull": [
            "inventory-analytics.component.html"
        ],
        "trophy": [
            "inventory-analytics.component.html",
            "sales-analytics.component.html"
        ],
        "settings": [
            "operational-metrics.component.html",
            "dev-layout.component.ts"
        ],
        "cart": [
            "sales-analytics.component.html"
        ],
        "tag": [
            "sales-analytics.component.html"
        ],
        "refresh": [
            "config.component.ts",
            "i18n-studio.component.ts",
            "log-explorer.component.ts",
            "state-inspector.component.ts"
        ],
        "trash-2": [
            "data-seeder.component.ts"
        ],
        "sun": [
            "data-seeder.component.ts"
        ],
        "server": [
            "data-seeder.component.ts"
        ],
        "alert-octagon": [
            "data-seeder.component.ts"
        ],
        "bell": [
            "data-seeder.component.ts"
        ],
        "database": [
            "dev-layout.component.ts"
        ],
        "file-text": [
            "dev-layout.component.ts"
        ],
        "camera": [
            "dev-layout.component.ts",
            "state-inspector.component.ts"
        ],
        "map": [
            "dev-layout.component.ts"
        ],
        "globe": [
            "dev-layout.component.ts"
        ],
        "palette": [
            "dev-layout.component.ts"
        ],
        "eye": [
            "firestore-monitor.component.ts",
            "approval-card.component.ts"
        ],
        "info": [
            "firestore-monitor.component.ts",
            "log-explorer.component.ts"
        ],
        "search": [
            "log-explorer.component.ts",
            "route-visualizer.component.ts"
        ]
    },
    "categories": {
        "modules": [
            "box",
            "users",
            "shopping-cart",
            "file-text",
            "settings",
            "database",
            "clipboard",
            "tool",
            "truck",
            "gift",
            "percent",
            "tag"
        ],
        "kpis": [
            "activity",
            "trending-up",
            "trending-down",
            "trending-neutral",
            "dollar-sign",
            "pie-chart",
            "bar-chart",
            "trophy",
            "target",
            "zap",
            "clock",
            "wallet",
            "credit-card",
            "banknote"
        ],
        "actions": [
            "edit",
            "trash",
            "trash-2",
            "search",
            "filter",
            "download",
            "upload",
            "share",
            "copy",
            "plus",
            "minus",
            "x",
            "check",
            "refresh",
            "refresh-cw",
            "login",
            "logout",
            "eye",
            "eye-off",
            "save",
            "bell",
            "send",
            "printer",
            "lock",
            "unlock"
        ],
        "navigation": [
            "home",
            "menu",
            "arrow-left",
            "arrow-right",
            "arrow-up",
            "arrow-down",
            "chevron-left",
            "chevron-right",
            "chevron-up",
            "chevron-down",
            "grid",
            "list",
            "folder",
            "map",
            "globe",
            "calendar"
        ],
        "status": [
            "check-circle",
            "x-circle",
            "alert-circle",
            "alert-triangle",
            "info",
            "help-circle",
            "shield",
            "wifi",
            "wifi-off",
            "server",
            "battery",
            "sun",
            "moon",
            "star",
            "heart",
            "flag"
        ]
    },
    "defined": [
        "lightning",
        "activity",
        "wallet",
        "box",
        "trending-up",
        "alert-triangle",
        "skull",
        "banknote",
        "refresh-cw",
        "trending-down",
        "trending-neutral",
        "users",
        "cart",
        "minus",
        "heart",
        "moon",
        "filter",
        "search",
        "grid",
        "database",
        "palette",
        "download",
        "edit",
        "trash",
        "refresh",
        "chevron-down",
        "chevron-right",
        "check-circle",
        "x-circle",
        "clock",
        "alert-circle",
        "info",
        "chart-bar",
        "chart-pie",
        "file-text",
        "document",
        "settings",
        "calendar",
        "command-center",
        "trophy",
        "briefcase",
        "scale",
        "target",
        "circle-fill",
        "dashboard",
        "arrow-left",
        "home",
        "log-out",
        "tag",
        "eye",
        "gift",
        "check",
        "x",
        "hourglass",
        "slash",
        "folder",
        "lock",
        "bell",
        "globe",
        "trash-2",
        "sun",
        "alert-octagon",
        "server",
        "layers",
        "shield",
        "tool",
        "camera",
        "paperclip",
        "list",
        "check-square",
        "user-check",
        "user",
        "credit-card",
        "map"
    ],
    "stats": {
        "total": 74,
        "used": 53,
        "unused": 21
    }
};
