/**
 * cart-hooks.ts
 * Cart abandonment detection, recovery queues, order completion hooks,
 * review request pipeline, referral tracking.
 */
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import { db } from './shared';

export const onCartAbandoned = functions.firestore
    .document('cartSnapshots/{snapId}')
    .onCreate(async (snap, context) => {
        const data = snap.data();
        if (data?.event !== 'abandoned_detected') return null;

        const sessionId = data.sessionId || context.params.snapId;
        const email = data.customerEmail || data.attribution?.email || null;
        const phone = data.customerPhone || null;
        const name = data.customerName || data.attribution?.name || 'Cliente';
        const items = data.items || [];
        const cartValue = data.cartValue || 0;
        const cartLink = 'https://importadoraeuro.com/checkout';

        if (!email && !phone) {
            // Cannot recover anonymous guest with no contact info — skip
            return null;
        }

        // Check if this session already has a recovery task
        const existing = await db.collection('recovery_queue')
            .where('sessionId', '==', sessionId)
            .limit(1).get();
        if (!existing.empty) return null; // already queued

        const now = Date.now();
        const batch = db.batch();

        // Step 1: 1 hour from now — friendly reminder
        const step1Ref = db.collection('recovery_queue').doc();
        batch.set(step1Ref, {
            sessionId, email, phone, name, items, cartValue,
            step: 1,
            sendAt: admin.firestore.Timestamp.fromMillis(now + 60 * 60 * 1000),
            status: 'pending',
            type: 'cart_recovery',
            message: `Hola ${name}, dejaste tu carrito con ${items.length} producto(s) por $${cartValue} MXN. ¿Te ayudamos a completar tu compra? 👉 ${cartLink}`,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        // Step 2: 24 hours from now — with coupon
        // Auto-generate a unique 5% coupon code
        const couponCode = `CART${sessionId.slice(-6).toUpperCase()}`;
        const step2Ref = db.collection('recovery_queue').doc();
        batch.set(step2Ref, {
            sessionId, email, phone, name, items, cartValue,
            step: 2,
            sendAt: admin.firestore.Timestamp.fromMillis(now + 24 * 60 * 60 * 1000),
            status: 'pending',
            type: 'cart_recovery',
            couponCode,
            message: `${name}, aquí tienes un 5% de descuento exclusivo: ${couponCode}. Válido por 48 horas. Completa tu compra → ${cartLink}`,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        await batch.commit();

        // Pre-create the coupon in Firestore so it's ready when the customer arrives
        const couponEndDate = new Date(now + 48 * 60 * 60 * 1000);
        await db.collection('coupons').doc(couponCode).set({
            code: couponCode,
            type: 'percentage',
            value: 5,
            isActive: true,
            usageLimit: 1,
            usageCount: 0,
            minPurchaseAmount: 0,
            startDate: admin.firestore.Timestamp.now(),
            endDate: admin.firestore.Timestamp.fromDate(couponEndDate),
            description: `Recuperación de carrito — sesión ${sessionId}`,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
            autoGenerated: true,
            source: 'cart_recovery',
        }, { merge: true });

        console.log(`[CartRecovery] Queued 2-step recovery for session ${sessionId}`);
        return null;
    });

// Processes pending recovery_queue items and writes to notification_outbox.
// Schedule: every 30 minutes. Outbox is read by any notification provider.
export const processRecoveryQueue = functions.pubsub
    .schedule('every 30 minutes')
    .onRun(async () => {
        const now = admin.firestore.Timestamp.now();
        const snap = await db.collection('recovery_queue')
            .where('status', '==', 'pending')
            .where('sendAt', '<=', now)
            .limit(50)
            .get();

        if (snap.empty) return null;

        const batch = db.batch();
        for (const docSnap of snap.docs) {
            const task = docSnap.data();

            // Write to notification_outbox — provider (WhatsApp/email) picks this up
            const outboxRef = db.collection('notification_outbox').doc();
            batch.set(outboxRef, {
                channel: task.phone ? 'whatsapp' : 'email',
                to: task.phone || task.email,
                name: task.name,
                message: task.message,
                type: task.type,
                step: task.step,
                couponCode: task.couponCode || null,
                sessionId: task.sessionId,
                status: 'queued',
                createdAt: admin.firestore.FieldValue.serverTimestamp(),
            });

            // Mark task as sent
            batch.update(docSnap.ref, {
                status: 'sent',
                sentAt: admin.firestore.FieldValue.serverTimestamp(),
            });
        }

        await batch.commit();
        console.log(`[RecoveryQueue] Dispatched ${snap.size} notifications to outbox.`);
        return null;
    });

// ─── Phase 2.2 — Product Review Request ─────────────────────────────────────
// Triggered when a new order is created (payment completed).
// Queues a review request 7 days later in review_requests collection.

export const onOrderCompleted = functions.firestore
    .document('orders/{orderId}')
    .onCreate(async (snap, context) => {
        const order = snap.data();
        if (!order) return null;

        const email = order.customerEmail || order.email;
        const phone = order.customerPhone || null;
        const name = order.customerName || order.name || 'Cliente';
        const items = (order.items || []).map((i: any) => ({
            productId: i.productId || i.id,
            productName: i.name || i.productName,
            slug: i.slug,
        }));

        if (!email && !phone) return null; // no contact info
        if (!items.length) return null;

        // Schedule review request 7 days from now
        const sendAt = admin.firestore.Timestamp.fromMillis(
            Date.now() + 7 * 24 * 60 * 60 * 1000
        );

        await db.collection('review_requests').doc(context.params.orderId).set({
            orderId: context.params.orderId,
            email, phone, name, items,
            sendAt,
            status: 'pending',
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        console.log(`[ReviewRequest] Queued for order ${context.params.orderId} — send at ${sendAt.toDate()}`);
        return null;
    });

// Processes pending review requests and publishes to notification_outbox.
// Schedule: daily at 10:00 AM Mexico City time.
export const processReviewRequests = functions.pubsub
    .schedule('0 10 * * *')
    .timeZone('America/Mexico_City')
    .onRun(async () => {
        const now = admin.firestore.Timestamp.now();
        const snap = await db.collection('review_requests')
            .where('status', '==', 'pending')
            .where('sendAt', '<=', now)
            .limit(100)
            .get();

        if (snap.empty) return null;

        const batch = db.batch();
        for (const docSnap of snap.docs) {
            const req = docSnap.data();
            const firstItem = req.items?.[0];
            const reviewUrl = firstItem?.slug
                ? `https://importadoraeuro.com/product/${firstItem.slug}?review=1`
                : 'https://importadoraeuro.com';

            const outboxRef = db.collection('notification_outbox').doc();
            batch.set(outboxRef, {
                channel: req.phone ? 'whatsapp' : 'email',
                to: req.phone || req.email,
                name: req.name,
                type: 'review_request',
                orderId: req.orderId,
                reviewUrl,
                message: `Hola ${req.name}, ¿cómo quedó tu llanta? Nos encantaría saber tu opinión. Deja tu reseña en 1 minuto: ${reviewUrl}`,
                status: 'queued',
                createdAt: admin.firestore.FieldValue.serverTimestamp(),
            });

            batch.update(docSnap.ref, {
                status: 'sent',
                sentAt: admin.firestore.FieldValue.serverTimestamp(),
            });
        }

        await batch.commit();
        console.log(`[ReviewRequests] Dispatched ${snap.size} review requests.`);
        return null;
    });

// ─── Phase 2.4 — Referral Program ────────────────────────────────────────────
// When an order is placed with a valid ?ref=CUSTOMERID attribution param,
// reward the referrer with a $100 MXN coupon after the order is confirmed.

export const onReferralOrderCompleted = functions.firestore
    .document('orders/{orderId}')
    .onCreate(async (snap, context) => {
        const order = snap.data();
        if (!order) return null;

        const referrerId = order.attribution?.ref || order.referrerId;
        if (!referrerId) return null; // no referral

        // Prevent self-referral
        const ordererUid = order.userId || order.uid;
        if (ordererUid && ordererUid === referrerId) return null;

        // Check if referrer already got a referral reward for this referee
        const existing = await db.collection('referral_rewards')
            .where('referrerId', '==', referrerId)
            .where('refereeOrderId', '==', context.params.orderId)
            .limit(1).get();
        if (!existing.empty) return null; // already rewarded

        // Generate unique coupon code for the referrer
        const couponCode = `REF${referrerId.slice(-5).toUpperCase()}${Date.now().toString(36).toUpperCase().slice(-3)}`;
        const couponEndDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days

        const batch = db.batch();

        // Create referrer reward coupon
        const couponRef = db.collection('coupons').doc(couponCode);
        batch.set(couponRef, {
            code: couponCode,
            type: 'fixed',
            value: 100,
            isActive: true,
            usageLimit: 1,
            usageCount: 0,
            minPurchaseAmount: 0,
            startDate: admin.firestore.Timestamp.now(),
            endDate: admin.firestore.Timestamp.fromDate(couponEndDate),
            description: `Premio de referido — referidor: ${referrerId}`,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
            autoGenerated: true,
            source: 'referral',
        });

        // Log the referral reward
        const rewardRef = db.collection('referral_rewards').doc();
        batch.set(rewardRef, {
            referrerId,
            refereeOrderId: context.params.orderId,
            refereeEmail: order.customerEmail || order.email || null,
            couponCode,
            value: 100,
            currency: 'MXN',
            status: 'issued',
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        // Queue notification to referrer
        // Look up referrer email from customers/orders
        const referrerOrders = await db.collection('orders')
            .where('userId', '==', referrerId).limit(1).get();
        const referrerEmail = referrerOrders.empty
            ? null
            : referrerOrders.docs[0].data().customerEmail || referrerOrders.docs[0].data().email;

        if (referrerEmail) {
            const outboxRef = db.collection('notification_outbox').doc();
            batch.set(outboxRef, {
                channel: 'email',
                to: referrerEmail,
                type: 'referral_reward',
                couponCode,
                message: `¡Tu amigo realizó su primera compra! Aquí está tu recompensa de $100 MXN: ${couponCode}. Válido por 30 días.`,
                status: 'queued',
                createdAt: admin.firestore.FieldValue.serverTimestamp(),
            });
        }

        await batch.commit();
        console.log(`[Referral] Rewarded referrer ${referrerId} with coupon ${couponCode} for order ${context.params.orderId}`);
        return null;
    });


// ═══════════════════════════════════════════════════════════════════════════════
// AMAZON SP-API INTEGRATION
// Auth: LWA-only (no SigV4 required since Oct 2, 2023)
// Marketplace: Mexico (A1AM78C64UM0Y8)  |  Region endpoint: sellingpartnerapi-na
// ═══════════════════════════════════════════════════════════════════════════════
